### ISSUE TITLE
Can't build shaderc

### ISSUE THREAD

**Issue by javl** [openframeworks-vk/openFrameworks#1]
I'm trying to get your Vulkan renderer to work on my system (Debian Stretch 'testing') in the hope of being able to use the HTC Vive with OF (with the default renderer it runs at just 30FPS; according to the SteamVR repo OpenGL is too slow and you'll have to use Vulkan).

Following your instructions, I'm trying to build `glfw` and `shaderc`. glfw is no problem, but when I try to build `shaderc` I get an error at about 89%:

    shaderc/libshaderc_util/include/libshaderc_util/counting_includer.h:42:65: error:
    ‘glslang::TShader::Includer::IncludeType’ has not been declared

And indeed, I'm not able to find a definition of `IncludeType` anywhere. Seeing as you've managed to build `shaderc` I'm not sure if this is a problem with glslang or something else...
Do you have any idea what I could be doing wrong?

Also: thanks a lot for working on this!

**Update**
`IncludeType` does seem to be [defined in shaderc itself](https://github.com/google/shaderc/blob/dd79e703a7d6bfe01565cbdb49f1ef1f8df057b2/libshaderc_util/include/libshaderc_util/counting_includer.h#L36) as an enum, so I'm messing around with that, see if I can get anything to work.

**Comment by javl** [comment]
I got it to work!
It might be useful to figure out what exactly went wrong for future use (as apparently the instructions for Linux are not up to date / complete), so I won't close this issue until you've been able to see it.

This is what I found:
I ran the `./apothecary -a 64 -t linux64 update shaderc` script once so it downloaded all of the git repos allowing me to make some changes in their files. I disabled the `git clone ...` lines in the shaderc formula afterwards so it didn't try to clone them again on the next run.

The first error was fixed by adding the missing `IncludeType` to `class Includer { public:` inside `shaderLang.h`:

    enum class IncludeType {
        System,  // Only do < > include search
        Local,   // Only do " " include search
    };

After that I got some other small errors which I could quickly fix. A bit odd though; one error was a variable `user_data` not existing and the script suggested I might wanted to use `userData`, which did work. I'd think an error like that should have been obvious to other users of shaderc so I'm not sure what happened there.

Anyway, after about three of these kind of simple errors I managed to build shaderc and with that compile `testVK` and `testVKDoubleBuffer`. `testVkFun` doesn't work:

    [notice ] Current fps: 60
    terminate called after throwing an instance of 'std::system_error'
        what():  vk::Device::createImage: ErrorValidationFailedEXT
    Aborted

But even though the other examples did work, they ran at about 60FPS, still too slow for VR :(

**Comment by tgfrerer** [comment]
Hey @javl ! great you find this useful.

I've used `testVkFun` recently to test rendering head-less, i.e. to an image swapchain only. If you switch out [these two lines](https://github.com/openframeworks-vk/openFrameworks/blob/vk/apps/devApps/testVkFun/src/main.cpp#L16) initialising the main window in `main.cpp` as a glfw window it should use standard, i.e. windowed rendering. 

To get the very highest framerates, I recommend using `Mailbox` as the swapchain present mode, something you can also set in `main.cpp`. Also make sure to set the framerate to 0 on the oF-side, like it's done [here](https://github.com/openframeworks-vk/openFrameworks/blob/vk/apps/devApps/testVkFun/src/ofApp.cpp#L56), so that frames are generated at maximum rate.

I'm getting frame rates of > 1700 fps, especially in release mode. Mailbox means to render at the highest rate and only present the latest frame upon vsync. Mailbox shouldn't tear, but it might not be available on some systems. It's worth trying out different present modes. Note that only Fifo is required by Vulkan to be present, so some present modes may not be available depending on your hardware/OS/driver combination. Out of curiosity: what's your config?

Note that there's a difference in drivers between linux and windows, it appears that currently for some things on NVIDIA the windows driver allows you to do slightly more things.

**Comment by javl** [comment]
It seems the example already uses Mailbox (`::vk::PresentModeKHR::eMailbox`) but when running I get:

    [warning] Could not switch to selected Swapchain Present Mode. Falling back to FIFO...
So it seems that mode is not available at the moment. I'm not sure if that means it is not in the Linux SDK, or if I have to somehow install / enable it. I'll look into it.

---
**edit:**
Running `./vulkaninfo` I found this which seems to confirm the Mailbox rendermode is not available:

    Present Modes:          count = 3
        FIFO_KHR
        FIFO_RELAXED_KHR
        IMMEDIATE_KHR

**edit 2:**
Using `::vk::PresentModeKHR::eFifoRelaxed` can create some tearing according to the docs, but it does add about 15FPS (around 78FPS in the demo).
The third one hits an amazing 6000FPS! though the docs mention:

    // VK_PRESENT_MODE_IMMEDIATE_KHR is for applications that don't care about
    // tearing, or have some way of synchronizing their rendering with the display.

So I'll have to check what tearing will do in VR. But I'd say it's very promising! I can imagine taking it down to the needed 90 FPS will already prevent some tearing. I'll see if I can create a simple example to try it out.

---
I also noticed OF doesn't actually use the Vulkan SDK I installed in ~/sdks as per your instructions but a slightly older version (1.0.42 vs 1.0.46 I believe) which I think came with SteamVR. I think you initially used an older version so it shouldn't matter much I think?

I'm running Debian Stretch (the testing branch) using the 375.27.15 NVidia driver (as it is the mandatory driver for SteamVR) with a GTX 1080 and i5-7500 CPU (3.40GHz).

To be honest I get the big picture but a lot of the specifics of swapchains, videodrivers and render modes are a bit over my head still, so thanks for the help.
I really think getting this to work so you can use OF with the Vive would be really cool and will open a lot of new options.

---

**update 3:**
I tried to convert the example for `ofxOpenVR` to use the Vulkan renderer but of course it's not as straight forward as I hoped it would be. Apart from getting the addon to work, it will also take some extra work to be able to draw the shapes and objects that I want, so I'm afraid I'm not going to be able to get this to work, or it will take a looong time.

**Comment by tgfrerer** [comment]
yes, ofxOpenVR seems (as far as i can see depend a bit on openGL) it should be fairly straightforward to convert it to vulkan, and some of the architectural choices in the vulkan renderer (i.e. draw commands which you can reuse amongst both eyes) should make it a bit easier, but yeah, probably about a couple of weeks work =) 

Great you saw these frame rates. Let me know if you're interested in vulkan per se, I've got a blog post prepared and am wondering about making a nice demo to showcase it, but I don't have a Vive at the moment, so can't really test out that side of things...

**update:**

Seems the openVR has some vulkan specific methods for presenting, so i would think implementing an openVR specific swapchain (similar to the swapchain i implemented for the offline-renderer) might be a way forward. I might buy one of these VR headsets one day to test it out =P

**Comment by javl** [comment]
> it should be fairly straightforward to convert it to vulkan

I'll have to figure out if I'm able to do it. Don't want to spend a lot of time on it and end up with something thats not really working

> Great you saw these frame rates.

I still have to check what it will do in VR, but it seems promising, right? Like I said, taking the framerate down might help to prevent tearing and hopefully Mailbox will be supported at some point as well.

> Let me know if you're interested in vulkan per se

Some more background info is always welcome to help understand what I'm looking at.

If you have a demo you want me to check on my system, let me know. I'm still not able to run testVKFun though. The window closes immediately because of a segmentation fault.
Unfortunately, with my current setup (I'm working in Sublime Text and `make` directly) I'm not really able to debug. Using `make Debug` with your examples fails because it can't find the debug files for Vulkan (might be because it uses the SteamVR files, as mentioned before):

    terminate called after throwing an instance of 'std::system_error'
        what():  vk::createInstance: ErrorLayerNotPresent

So yeah, I kind of know whats going on, but not really ;) Need some more time.

**Comment by tgfrerer** [comment]
Re: the orignal issue - I've just merged of-vk with openFrameworks master, and updated the recipes for shaderc in apothecary. The compile error was due to the apothecary recipe downloading an older version of the source for shaderc than for its dependencies. This should be fixed now.

I'm closing this issue but feel free to open other issues if you find any other stumbling blocks.
